### ISSUE TITLE
Update for Iosevka 3.

### ISSUE THREAD

**Issue by mreishus** [mreishus/ttf-iosevka-haskell-git#1]
Iosevka 3 has been released and the build process might be different.

There's now 3 levels: Iosevka (all ligatures), Iosevka Term (ligatures for terminals), Iosevka Fixed (no ligatures).  This might need to go to the middle level now.

I found an example of a working custom build, it might help.

build.sh
```
$ npm run build -- contents::iosevka-jdk contents::iosevka-jdk-slab
```

private-build-plans.toml
```toml
[buildPlans.iosevka-jdk]
family = "Iosevka JDK"
design = ["cv19", "cv67"]
hintParams = ["-a", "nnn"]

[buildPlans.iosevka-jdk.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-jdk.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-jdk.slants]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-jdk.widths.normal]
shape = 7
menu  = 5
css   = "normal"

[buildPlans.iosevka-jdk.widths.condensed]
shape = 5
menu  = 3
css   = "condensed"

[buildPlans.iosevka-jdk-slab]
family = "Iosevka JDK Slab"
design = ["slab", "cv19", "cv67"]
hintParams = ["-a", "nnn"]

[buildPlans.iosevka-jdk-slab.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-jdk-slab.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevka-jdk-slab.slants]
upright = "normal"
italic  = "italic"

[buildPlans.iosevka-jdk-slab.widths.normal]
shape = 7
menu  = 5
css   = "normal"

[buildPlans.iosevka-jdk-slab.widths.condensed]
shape = 5
menu  = 3
css   = "condensed"
```
